rootProject.name = "aoc-2021"
include("day-1")
include("day-2")
include("day-3")
include("day-4")
include("day-5")
include("day-6")
include("day-7")
include("day-8")
include("day-9")
include("day-10")
